### PR TITLE
feat: Install Application-Flask template

### PR DESCRIPTION
**Pull request by KevinJBoyer**
## Ticket

Resolves https://navalabs.atlassian.net/browse/DST-259 

## Changes
 - Install the Application-Flask template
 - Configure with the project name
 - Enable setting local secrets, add this to set up documentation
 - Add a PR template (porting over from the labs-gen-ai-experiments repo)

## Context for reviewers
 - I recommend you review only [the second commit in this PR](https://github.com/navapbc/labs-decision-support-tool/pull/1/commits/0858c10f949077bb13b767e1eb5359afd6a63910); the first is the output purely from running the template install script. The second commit contains the actual custom changes.

## Testing
You should be able to follow the local set up instructions, and then navigate to http://localhost:8080 and see:
image

### CODE REVIEW

**Review by ccheng26 — APPROVED** [review]
lgtm, local set up instructions tested successfully

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 0 | 0 | 0 | NaN% |

[View detailed results in Google Sheets]()

**» View eval results in CI console «**

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 0 | 0 | 0 | NaN% |

[View detailed results in Google Sheets]()

**» View eval results in CI console «**

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 0 | 0 | 0 | NaN% |

[View detailed results in Google Sheets]()

**» View eval results in CI console «**

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 0 | 0 | 0 | NaN% |

[View detailed results in Google Sheets]()

**» View eval results in CI console «**

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 0 | 0 | 0 | NaN% |

[View detailed results in Google Sheets](https://docs.google.com/spreadsheets/d/1xpOBO7FnRgmgILYwn0gj_LGqqdpi-E5cfQxdgscw21s/edit)

**» View eval results in CI console «**

**Comment by fg-nava** [comment]
## Promptfoo Evaluation Results

| Success | Failure | Total | Pass Rate |
|---------|---------|-------|-----------|
| 2 | 0 | 2 | 100.00% |

[View detailed results in Google Sheets](https://docs.google.com/spreadsheets/d/1xpOBO7FnRgmgILYwn0gj_LGqqdpi-E5cfQxdgscw21s/edit)

**» View eval results in CI console «**

**Pull request merged**
